# Unit: MusicLibrary — the soundtrack bank (Phase 14, GDD §7).
# The files are generated by tools/utils/gen_audio.py (fixed seed,
# byte-stable) — these checks pin their contract: lengths, levels,
# loop flags, and that the five variations are distinct.
extends Node

const _M = preload("res://scripts/audio/music_library.gd")


func run(ctx: Variant) -> void:
	var variants: Dictionary = {
		"normal": _M.wound("normal"),
		"memory": _M.wound("memory"),
		"echo": _M.wound("echo"),
		"archivist": _M.wound("archivist"),
		"ending": _M.wound("ending"),
	}
	for k in variants:
		var w: AudioStreamWAV = variants[k]
		ctx.check(w != null, "music %s: loads" % k)
		var dur: float = _M.duration(w)
		ctx.check(dur >= 24.0 and dur < 30.0,
				"music %s: ~24s (got %.1f)" % [k, dur])
		var pk: float = _M.peak(w)
		ctx.check(pk < 0.9, "music %s: no clipping (peak %.2f)" % [k, pk])
		ctx.check(pk > 0.2, "music %s: not silent (peak %.2f)" % [k, pk])
		ctx.check(_M.is_looping(w), "music %s: loops" % k)
	# The variations differ: memory carries the reverb tail (longer)
	# and where equal-length, the bytes differ.
	var a: PackedByteArray = variants["normal"].data
	var b: PackedByteArray = variants["memory"].data
	var differ: bool = a.size() != b.size()
	if not differ:
		for i in range(0, mini(a.size(), b.size()) - 1, 37):
			if a[i] != b[i]:
				differ = true
				break
	ctx.check(differ, "music: normal != memory")
	var arch: PackedByteArray = variants["archivist"].data
	var norm: PackedByteArray = variants["normal"].data
	var differ2: bool = true
	for i in range(0, mini(arch.size(), norm.size()) - 1, 53):
		if arch[i] != norm[i]:
			break
		differ2 = false
	ctx.check(differ2, "music: normal != archivist")

	var amb: Dictionary = {
		"camp": _M.ambient(&"camp"),
		"wild": _M.ambient(&"ruined_village"),
		"stone": _M.ambient(&"old_shrine"),
		"mine": _M.ambient(&"the_mine"),
		"lake": _M.ambient(&"mysterious_lake"),
		"undercroft": _M.ambient(&"undercroft"),
	}
	for k in amb:
		var w: AudioStreamWAV = amb[k]
		ctx.check(w != null, "amb %s: loads" % k)
		var dur: float = _M.duration(w)
		ctx.check(absf(dur - 16.0) < 0.05, "amb %s: 16s (got %.2f)" % [k, dur])
		var pk: float = _M.peak(w)
		ctx.check(pk < 0.5, "amb %s: bed level (peak %.2f)" % [k, pk])
		ctx.check(pk > 0.05, "amb %s: not silent (peak %.2f)" % [k, pk])
		ctx.check(_M.is_looping(w), "amb %s: loops" % k)
	# Every zone in the layout resolves to an ambient (no silence).
	for zone in ["camp", "ruined_village", "watchtower", "the_mine",
			"old_shrine", "broken_bridge", "mysterious_lake", "ancient_gate",
			"undercroft"]:
		ctx.check(_M.ambient(zone) != null, "amb: %s resolves" % zone)

	var st: AudioStreamWAV = _M.stinger()
	ctx.check(st != null, "stinger: loads")
	var sd: float = _M.duration(st)
	ctx.check(absf(sd - 4.0) < 0.05, "stinger: 4s (got %.2f)" % sd)
	var sp: float = _M.peak(st)
	ctx.check(sp < 0.9 and sp > 0.3, "stinger: level (peak %.2f)" % sp)
	ctx.check(not _M.is_looping(st), "stinger: one-shot")

	# The unknown-name guards (no crash, an error, null).
	ctx.check(_M.wound("nope") == null, "music: unknown variation -> null")
	ctx.check(_M.ambient(&"nowhere") == null, "amb: unknown zone -> null")
